language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "10"

cache:
  directories:
    - node_modules

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm config set spin false
